website/sahayak/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from sahayak import settings

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'pages.views.home', name='home'),
    url(r'^categories$', 'pages.views.categorylist', name='categorylist'),
    url(r'^signup/', 'pages.views.signup', name='signup'),
    url(r'^login/', 'pages.views.login', name='login'),
    url(r'^logout/', 'pages.views.logout', name='logout'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^category/(?P<category_name>[A-Za-z0-9_;:-]+)$', 'pages.views.categorypage', name='categorypage'),
    url(r'^(?P<worker_number>\d+)$', 'pages.views.workerpage', name='workerpage'),
    url(r'^hire/(?P<worker_number>\d+)$', 'pages.views.hireworker', name='hireworker'),
    url(r'^myjobs$', 'pages.views.myjobs', name='myjobs'),
    url(r'^workerjobs$', 'pages.views.workerjobs', name='workerjobs'),
    url(r'^workeraction/(?P<job_number>\d+)/(?P<action>[A-Za-z0-9_;:-]+)$', 'pages.views.workeraction', name='workeraction'),
    url(r'^admin/', include(admin.site.urls)),
)


if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
   )

website/pages/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image


class Media(models.Model):
    '''
    Represents the image file as media
    It processes and saves the media file in fixed
    size upon saving.
    '''
    image = models.ImageField()
    description = models.CharField(max_length=1000, default=' ')

    # def save(self, size=(200, 200)):
    #     """
    #     Save Photo after ensuring it is not blank.  Resize as needed.
    #     """
    #     from sahayak import settings

    #     if not self.image:
    #         return

    #     super(Media, self).save()

    #     filename = settings.MEDIA_ROOT+"/"+self.image.name
    #     image = Image.open(filename)
    #     width, height = image.size
    #     if height > width:
    #         ratio = height/width

    #         image.thumbnail((200, 200*ratio), Image.ANTIALIAS)
    #     else:
    #         ratio = width/height
    #         image.thumbnail((200*ratio, 200), Image.ANTIALIAS)
    #     image.save(filename)

    def showimage(self):
        return '<img src="/media/'+self.image.name+'"/>'
    showimage.allow_tags = True

    def geturl(self):
        '''
        Returns the URL of the media file
        '''
        pass

    def __str__(self):
        return self.description


class Field(models.Model):
    name = models.CharField(max_length=100)
    slug = models.CharField(max_length=100)
    image = models.ForeignKey(Media, null=True, blank=True)
    workername = models.CharField(max_length=100, default='')

    def __str__(self):
        return self.name


class WorkerInfo(models.Model):
    user = models.ForeignKey(User)
    image = models.ForeignKey(Media, null=True, blank=True)
    field = models.ManyToManyField(Field, null=True, blank=True, related_name="workerinfo" , related_query_name="worker")
    totalrating = models.IntegerField(default=0)
    rating = models.FloatField(default=0)
    ratingcount = models.IntegerField(default=0)
    phonenumber = models.CharField(max_length=100)
    about = models.TextField(default='')

    def __str__(self):
        return "Worker info for "+self.user.first_name+" "+self.user.last_name

    def getname(self):
        return self.user.first_name+" "+self.user.last_name

    def jobscompleted(self):
        return Job.objects.filter(worker=self, status=Job.COMPLETED).count()

    def jobspending(self):
        return Job.objects.filter(worker=self, status=Job.ACCEPTED).count()

    def isbusy(self):
        # If the accepted jobs count of a user exceeds 3, then he is busy
        return self.jobspending() > 1

    def isexperienced(self):
        return self.jobscompleted() > 2

    def availability(self):
        if self.isbusy():
            return "Busy"
        return "Free"


    def addrating(self, ratingpoint):
        self.ratingcount += 1
        self.totalrating += ratingpoint
        self.rating = self.totalrating / (self.ratingcount * 1.0)
        self.save()

    def gettags(self):
        tags = ''
        if self.isbusy():
            tags += ' busy'
        else:
            tags += ' free'
        if self.rating > 4.0:
            tags += ' toprated'
        if self.isexperienced():
            tags += ' experienced'
        return tags

    def skills(self):
        list = []
        for field in self.field.all():
            list.append(field.name)
        return ",".join(list)


class Job(models.Model):
    customer = models.ForeignKey(User)
    worker = models.ForeignKey(WorkerInfo)

    title = models.CharField(max_length=1000, default='')
    description = models.TextField(default='')

    AWAITING = "AR"
    REJECTED = "RJ"
    ACCEPTED = "AC"
    COMPLETED = "CP"

    JOB_STATUS = (
        (AWAITING, "Awaiting Response"),
        (REJECTED, "Rejected"),
        (ACCEPTED, "Accepted"),
        (COMPLETED, "Completed")
    )
    status = models.CharField(max_length=2,
                              choices=JOB_STATUS,
                              default=AWAITING)

    rating = models.IntegerField(null=True, blank=True)
    ratingtext = models.CharField(max_length=1000, blank=True, default='')

    def __str__(self):
        return self.title+" for customer "+self.customer.first_name+" "+self.customer.last_name+" by "+self.worker.getname()

    def customerinfo(self):
        return UserInfo.objects.get(user=self.customer)

class UserInfo(models.Model):
    user = models.OneToOneField(User, related_name="userinfo", related_query_name="info")

    latitude=models.FloatField(default=0)
    longitude=models.FloatField(default=0)

website/pages/views.py
from django import forms
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib import auth
from django.template import RequestContext, loader
from django.http import HttpResponse,HttpRequest,HttpResponseRedirect
from django.shortcuts import render,redirect,get_object_or_404
from pages.models import Media,Field,WorkerInfo,Job,UserInfo


def isWorker(request):
    if not request.user.is_authenticated():
        return False
    return WorkerInfo.objects.filter(user=request.user).count() > 0

# Create your views here.
def login(request):
    if(request.method=='POST'):
        username=request.POST['username']
        password=request.POST['password']
        user=auth.authenticate(username=username,password=password)
        if user is not None:
            auth.login(request,user)
            return redirect('categorylist')
        else:
            return render(request,'login.html',{'message':'Invalid login'})
    else:
        return render(request, 'login.html')

def logout(request):
    auth.logout(request)
    return redirect('home')

def home(request):
    template = loader.get_template('home.html')
    context = RequestContext(request, {
        'isworker': isWorker(request),
        'title': "Sahayak",
        'mainmenuindex': 1,
    })

    return HttpResponse(template.render(context))

class SignupForm(forms.Form):
    firstname = forms.CharField(
        required=True,
        max_length = 20,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'First Name',
                'required':'required'
            },
        ),
        error_messages={'required': "You must enter your First Name."}
    )

    lastname = forms.CharField(
        required=True,
        max_length = 20,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Last Name',
                'required':'required'
            },
        ),
        error_messages={'required': "You must enter your Last Name."}
    )

    username = forms.CharField(
        required=True,
        min_length=5,
        max_length=20,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Username',
                'required':'required'
            },
        ),
        error_messages={'required': "You must enter a Username."}
    )

    password = forms.CharField(
        required=True,
        min_length=5,
        max_length=20,
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Enter you password',
                'required':'required',
            },
        ),
        error_messages={'required': "You must enter a Password."}
    )

    email = forms.EmailField(
        label='Your Email',
        required=True,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Email Address',
                'required':'required'
            },
        ),
    )

    latitude = forms.CharField(
        required=True,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'required':'required',
                'readonly':''
            },
        ),
    )

    longitude = forms.CharField(
        required=True,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'required':'required',
                'readonly':''
            },
        ),
    )


def signup(request):
        if(request.method=='POST'):
            form = SignupForm(request.POST)
            if form.is_valid():
                firstname = form.cleaned_data['firstname']
                lastname = form.cleaned_data['lastname']
                username = form.cleaned_data['username']
                password = form.cleaned_data['password']
                email = form.cleaned_data['email']

                latitude = request.POST['latitude']
                longitude = request.POST['longitude']

                # check if the username or email is already registered
                user = auth.models.User.objects.create_user(username, email, password)
                user.first_name=firstname
                user.last_name=lastname
                user.save()

                userinfo = UserInfo(user=user,latitude=latitude,longitude=longitude)
                userinfo.save()

                user = auth.authenticate(username=username, password=password)
                return HttpResponse('User created')
        else:
            form=SignupForm()
            return render(request,'signup.html',{'form':form})

def categorylist(request):
    template = loader.get_template('categories.html')

    categories = Field.objects.all()

    context = RequestContext(request, {
        'isworker': isWorker(request),
        'title': "Categories : Sahayak",
        'mainmenuindex': 2,
        'categories': categories,
    })

    return HttpResponse(template.render(context))


def categorypage(request, category_name):

    category = get_object_or_404(Field, slug=category_name)
    workers = WorkerInfo.objects.filter(field=category)

    template = loader.get_template('categorypage.html')
    context = RequestContext(request, {
        'title': "All workers working in category "+category.name,
        'mainmenuindex': 2,
        'category': category,
        'workers': workers,
        'isworker': isWorker(request),
    })

    return HttpResponse(template.render(context))


def workerpage(request, worker_number):
    worker = get_object_or_404(WorkerInfo, pk=worker_number)
    userinfo = UserInfo.objects.get(user=worker.user)
    template = loader.get_template('workerpage.html')

    comments = []
    commentobj = Job.objects.filter(worker=worker, status=Job.COMPLETED)
    for comobj in commentobj:
        if len(comobj.ratingtext) > 2:
            comment = {}
            comment["comment"] = comobj.ratingtext
            comment["by"] = comobj.customer.first_name+" "+comobj.customer.last_name
            comment["rating"] = comobj.rating
            comments.append(comment)

    commentscount = len(comments)

    context = RequestContext(request, {
        'title': "Info about  "+worker.getname(),
        'mainmenuindex': 2,
        'worker': worker,
        'comments': comments,
        'commentscount': commentscount,
        'userinfo': userinfo,
        'isworker': isWorker(request),
    })

    return HttpResponse(template.render(context))

class HireForm(forms.Form):

    def __init__(self, *args, **kwargs):
        kwargs.setdefault('label_suffix', '')
        super(HireForm, self).__init__(*args, **kwargs)

    subject = forms.CharField(
        label='Enter Title of Job',
        required=True,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'eg: Sink needs fixing'
            }
        ),
        error_messages={'required': "You must enter a title for your job."}
    )

    description = forms.CharField(
        label='Description of the job',
        required=True,
        widget=forms.Textarea(
            attrs={
                'class': 'form-control',
            }
        ),
        error_messages={'required': "You must enter a description for your job."}
    )

def hireworker(request, worker_number):
    worker = get_object_or_404(WorkerInfo, pk=worker_number)
    userinfo = UserInfo.objects.get(user=worker.user)
    template = loader.get_template('hireworker.html')

    created = False

    if request.method == 'POST':  # If the form has been submitted...
        form = HireForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            description = form.cleaned_data['description']
            # Save the object
            job = Job(
                customer=request.user,
                worker=worker,
                title=subject,
                description=description,
                status=Job.AWAITING,
            )
            job.save()
            created=True
    else:
        form = HireForm()

    context = RequestContext(request, {
        'title': "Hire  "+worker.getname(),
        'mainmenuindex': 2,
        'worker': worker,
        'userinfo': userinfo,
        'form': form,
        'success': created,
        'isworker': isWorker(request),
    })

    return HttpResponse(template.render(context))


def myjobs(request):
    template = loader.get_template('myjobs.html')

    myjobs = Job.objects.filter(customer = request.user)

    context = RequestContext(request, {
        'title': "My Jobs",
        'mainmenuindex': 3,
        'jobs': myjobs,
        'isworker': isWorker(request),
    })

    return HttpResponse(template.render(context))

def workerjobs(request):
    template = loader.get_template('workerjobs.html')

    myjobs = Job.objects.filter(worker__user = request.user)

    context = RequestContext(request, {
        'title': "My Incoming Jobs",
        'mainmenuindex': 4,
        'jobs': myjobs,
        'isworker': isWorker(request),
    })

    return HttpResponse(template.render(context))


def workeraction(request, job_number, action):
    job = Job.objects.get(pk=number)
    return HttpResponse(action)

website/pages/templates/base.html
{% load staticfiles %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>
      {{ title }}
    </title>

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/prettyPhoto.css' %}" rel="stylesheet">
    <link href="{% static 'css/animate.css' %}" rel="stylesheet">
    <link href="{% static 'css/main.css' %}" rel="stylesheet">

    <!--[if lt IE 9]>
    <script src="{% static 'js/html5shiv.js' %}"></script>
    <script src="{% static 'js/respond.min.js' %}"></script>
    <![endif]-->

    <link rel="shortcut icon" href="{% static 'images/ico/favicon.ico' %}">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{% static 'images/ico/apple-touch-icon-144-precomposed.png' %}">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{% static 'images/ico/apple-touch-icon-114-precomposed.png' %}">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{% static 'images/ico/apple-touch-icon-72-precomposed.png' %}">
    <link rel="apple-touch-icon-precomposed" href="{% static 'images/ico/apple-touch-icon-57-precomposed.png' %}">

    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.prettyPhoto.js' %}"></script>
    <script src="{% static 'js/jquery.isotope.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script>
      $.fn.stars = function() {
            return $(this).each(function() {
                $(this).html($('<span />').width(Math.max(0, (Math.min(5, parseFloat($(this).html())))) * 16));
            });
        }
    </script>

    <style type="text/css">
        span.stars, span.stars span {
            display: block;
            background: url({% static 'stars.png' %}) 0 -16px repeat-x;
            width: 80px;
            height: 16px;
        }

        span.stars span {
            background-position: 0 0;
        }
    </style>

  </head><!--/head-->
  <body>
    <header class="navbar navbar-inverse navbar-fixed-top wet-asphalt" role="banner">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}"><img src="{% static 'images/logo.png' %}" alt="logo"></a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li {% if mainmenuindex == 1 %}class="active" {% endif %}><a href="{% url 'home' %}">Home</a></li>
            {% if user.is_authenticated %}

            <li {% if mainmenuindex == 2 %}class="active" {% endif %}><a href="{% url 'categorylist' %}">Categories</a></li>
            <li {% if mainmenuindex == 3 %}class="active" {% endif %}><a href="{% url 'myjobs' %}">My Jobs</a></li>
            {% if isworker %}
            <li {% if mainmenuindex == 4 %}class="active" {% endif %}><a href="{% url 'workerjobs' %}">Jobs given to me</a></li>
            {% endif %}
            <li><a href="{% url 'logout' %}">Log Out</a></li>
            {% else %}
            <li {% if mainmenuindex == 3 %}class="active" {% endif %}><a href="{% url 'login' %}">Login</a></li>
            {% endif %}
          </ul>
        </div>
      </div>
    </header><!--/header-->

    {% block content %}
    {% endblock content %}

    <footer id="footer" class="midnight-blue">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    &copy; 2014 Sahayak. All Rights Reserved.
                </div>
            </div>
        </div>
    </footer><!--/#footer-->

    {% block scripts %}
    {% endblock %}
    <script>
      $('span.stars').stars();
    </script>
  </body>
</html>

website/pages/templates/categories.html
{% extends "base.html" %}{% load staticfiles %}

{% block content %}
<section id="portfolio" class="container">
  <ul class="portfolio-items col-3">
    {% for category in categories %}
    <li class="portfolio-item apps">
      <div class="item-inner">
        <a href="{% url 'categorypage' category.slug %}"><img src="/media/{{ category.image.image.name }}" alt=""></a>
        <h3 style="text-align:center;">{{ category.name }}</h3>
      </div>
    </li><!--/.portfolio-item-->
    {% endfor %}
  </ul>
</section><!--/#portfolio-->
{% endblock content %}

website/pages/templates/categorypage.html
{% extends "base.html" %}{% load staticfiles %}

{% block content %}

<div class="row">
  <div class="col-lg-12">
    <div class="center">
      <h2><strong>{{ category.workername }}</strong> near you</h2>
    </div>
    <div class="gap"></div>
  </div>
</div>


<section id="portfolio" class="container">

  <ul class="portfolio-filter">
    <li><a class="btn btn-default active" href="#" data-filter="*">All</a></li>
    <li><a class="btn btn-default" href="#" data-filter=".busy">Busy</a></li>
    <li><a class="btn btn-default" href="#" data-filter=".free">Free</a></li>
    <li><a class="btn btn-default" href="#" data-filter=".toprated">High Rated</a></li>
    <li><a class="btn btn-default" href="#" data-filter=".experienced">Experienced</a></li>
  </ul><!--/#portfolio-filter-->

  <ul class="portfolio-items col-3">
    {% for worker in workers %}
    <li class="portfolio-item {{ worker.gettags }}">
      <div class="item-inner">
        <a href="{% url 'workerpage' worker.pk %}"><img src="/media/{{ worker.image.image.name }}" alt=""></a>
        <h3 style="text-align:center;">{{ worker.getname }}</h3><br/>
        <div style="width:90px;margin:auto;"><span class="stars">{{ worker.rating }}</span></div><br/>
        <div style="text-align:center;">Availability : {{ worker.availability }}</div>
        <br/><br/>
      </div>
    </li><!--/.portfolio-item-->
    {% endfor %}
  </ul>
</section><!--/#portfolio-->

{% endblock content %}

website/pages/templates/hireworker.html
{% extends "base.html" %}{% load staticfiles %}

{% block content %}
<section id="contact-page" class="container">
  <div class="row">
    <div class="col-sm-4">
      <h3>Hire {{ worker.getname }}</h3>
      <a href="{% url 'workerpage' worker.pk %}"><img src="/media/{{ worker.image.image.name }}" alt="" style="width:300px;height:auto;"></a>
    </div>
    <div class="col-sm-8">
      {% if success %}
      <div class="notification success">
        <p>Your job has been successfully posted. We will notify you once the worker accepts your request.</p>
      </div>
      {% else %}
      <form method="POST" action="{% url 'hireworker' worker.pk %}">{% csrf_token %}
        <div class="form-group">
          {{form.subject.label_tag}}  {{ form.subject.errors }}
          {{ form.subject }}
        </div>
        <div class="form-group">
          {{form.description.label_tag}}  {{ form.description.errors }}
          {{ form.description }}
        </div>

        <div class="form-group">
          <button type="submit" class="btn btn-primary btn-lg">Submit Job</button>
        </div>

      </form>
      {% endif %}
    </div><!--/.col-sm-8-->
  </div>
</section><!--/#contact-page-->

{% endblock content %}

website/pages/templates/login.html
{% extends 'base.html' %}

{% block content %}
<section class="container" style="min-height:480px;">
    <div class="row">
        <div class="col-sm-8">
            
        </div>
        <div class="col-sm-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h2 class="panel-title">Enter you details</h2>
                </div>
                <div class="panel-body">
                    <form method="POST" action="{% url 'login' %}" role="form">
                    {% csrf_token %}
                    <div class="form-group">
                        <input class="form-control" type="text" name="username" placeholder="Username" required>
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="password" name="password" placeholder="Password" required>
                    </div>
                    <div class="checkbox">
                        <label>
                            <input name="remember" value="Remember Me" type="checkbox">Remember Me
                        </label>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-success btn-lg">Login</button>
                    </div>
                    <p>
                        <a href="{% url 'signup' %}">Create a new account</a>
                    </p>
                </form>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

website/pages/templates/myjobs.html
{% extends "base.html" %}{% load staticfiles %}

{% block content %}
<section id="contact-page" class="container">
  <div class="row">

    {% for job in jobs %}
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion{{forloop.counter}}" href="#collapseTwo{{forloop.counter}}">
            <strong>{{ job.title }}</strong> given to {{job.worker.getname}} description
          </a>
        </h4>
      </div>
      <div id="collapseTwo{{forloop.counter}}" class="panel-collapse collapse">
        <div class="panel-body">
          <strong>Job Description: </strong><br/>
          <p>{{job.description}}</p>
          <strong>Status: </strong><br/>
          <p>{{job.get_status_display}}</p>
                    <strong>Worker: </strong><br/>
                    <p><a href="{% url 'workerpage' job.worker.pk %}">{{job.worker.getname}}</a></p>

        </div>
      </div>
    </div>
    {% empty %}
    <p>No jobs. Please assign jobs to workers first.</p>
    {% endfor %}


  </div>
</section><!--/#contact-page-->

{% endblock content %}

website/pages/templates/signup.html
{% extends 'base.html' %}

{% block content %}
<section class="container">
    <div class="row">
    		<div class="col-sm-7">
                <h2>Choose you location</h2>
                <style>
                    #map-canvas {
                        height: 450px;
                        margin: 0px;
                        padding: 0px
                    }
                </style>
                <div id="map-canvas">
                </div>
    		</div>

        <div class="col-sm-5">
            <h3>Enter your details</h3>
            <form method="POST" action="{% url 'signup' %}" role="form">
                {% csrf_token %}
        		<div class="form-group">
                    {{ form.firstname.errors }}
          			{{ form.firstname }}
                </div>
                <div class="form-group">
                    {{ form.lastname.errors }}
          			{{ form.lastname }}
                </div>
                <div class="form-group">
                    {{ form.username.errors }}
          		    {{ form.username }}
                </div>
        		<div class="form-group">
                    {{ form.password.errors }}
          			{{ form.password }}
                </div>
                <div class="form-group">
                    {{ form.email.errors }}
          			{{ form.email }}
                </div>
                <div class="form-group">
                    <label>Latitude</label>
                    {{ form.latitude }}
                </div>
                <div class="form-group">
                    <label>Longitude</label>
                    {{ form.longitude }}
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-lg">Signup</button>
                </div>
            </form>
        </div>
    </div>
</section>
{% endblock %}


{% block scripts %}
<script>
    // It requires that you consent to location sharing when
    // prompted by your browser. If you see a blank space instead of the map, this
    // is probably because you have denied permission for location sharing.
    var map;
    var pos;
    var marker;


    function setPosition(pos){
        $('#id_latitude').val(pos.k);
        $('#id_longitude').val(pos.D);
    }

    function initialize() {
        var mapOptions = {
            zoom: 14
        };

        //Initialize google maps
        map = new google.maps.Map(document.getElementById('map-canvas'),mapOptions);

        // Try HTML5 geolocation
        if(navigator.geolocation){
            //Obtaining current position
            navigator.geolocation.getCurrentPosition(function(position){
                pos = new google.maps.LatLng(position.coords.latitude,position.coords.longitude);
                setPosition(pos);
                map.setCenter(pos);

                marker = new google.maps.Marker({
                    position: pos,
                    map: map,
                    draggable: true,
                });

                google.maps.event.addListener(marker, 'dragend', function(){
                    pos=marker.getPosition();
                    setPosition(pos);
                });

                google.maps.event.addListener(map, 'click', function(event) {
                    pos=event.latLng;
                    setPosition(pos);
                    if (marker) { 
                        marker.setMap(null) 
                    }
                    marker = new google.maps.Marker({ 
                        position: pos, 
                        map: map,
                        draggable: true,
                    });
                });                        
            },

            //Error occured
            function() {
                pos = new google.maps.LatLng(27.7, 85.33333330000005);
                map.setCenter(pos);
                setPosition(pos);

            });

        } else {
            // Browser doesn't support Geolocation
            pos = new google.maps.LatLng(27.7, 85.33333330000005);
            map.setCenter(pos);
            setPosition(pos);
        }
    }

    google.maps.event.addDomListener(window, 'load', initialize);
</script>
{% endblock %}

website/pages/templates/workerjobs.html
{% extends "base.html" %}{% load staticfiles %}

{% block content %}
<section id="contact-page" class="container">
  <div class="row">

    {% for job in jobs %}
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion{{forloop.counter}}" href="#collapseTwo{{forloop.counter}}">
            <strong>{{ job.title }}</strong> given by {{job.customer.first_name}} {{job.customer.last_name}}
          </a>
        </h4>
      </div>
      <div id="collapseTwo{{forloop.counter}}" class="panel-collapse collapse">
        <div class="panel-body">
          <strong>Job Description: </strong><br/>
          <p>{{job.description}}</p>
          <strong>Status: </strong><br/>
          <p>{{job.get_status_display}}</p>
          <strong>Map of Customer</strong>
          <iframe width="100%" height="315" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?q={{ job.customerinfo.latitude }},{{ job.customerinfo.longitude }}&hl=es;z=14&amp;output=embed"></iframe>
          <strong>Actions</strong>
          <br/><br/>
          <a href="{% url 'workeraction' job.pk 'accept'%}"><button class="btn btn-primary btn-lg">Accept</button></a>
          <a href="{% url 'workeraction' job.pk 'reject'%}"><button class="btn btn-danger btn-lg">Reject</button></a>
        </div>
      </div>
    </div>
    {% empty %}
    <p>No jobs. Please assign jobs to workers first.</p>
    {% endfor %}


  </div>
</section><!--/#contact-page-->

{% endblock content %}